""" add category.link and category.quantity

Revision ID: 314e597d5a6e
Revises: de26de15a288
Create Date: 2018-01-31 02:05:53.321151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314e597d5a6e'
down_revision = 'de26de15a288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('link', sa.String(), nullable=True))
    op.add_column('category', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'category', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'quantity')
    op.drop_column('category', 'link')
    # ### end Alembic commands ###
