"""empty message

Revision ID: 433885865648
Revises: 3297199125d0
Create Date: 2018-02-09 22:51:55.370470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433885865648'
down_revision = '3297199125d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affix_type', sa.Column('top', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affix_type', 'top')
    # ### end Alembic commands ###
