""" add affix_type.filter_name

Revision ID: 4685c092ad95
Revises: 9b34058bea95
Create Date: 2018-02-05 22:52:11.446489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4685c092ad95'
down_revision = '9b34058bea95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affix_type', sa.Column('filter_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affix_type', 'filter_name')
    # ### end Alembic commands ###
