""" add item.fated

Revision ID: 7959f466ec5b
Revises: 8105cb16dbda
Create Date: 2018-02-27 20:53:28.509046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7959f466ec5b'
down_revision = '8105cb16dbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('fated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'fated')
    # ### end Alembic commands ###
