"""empty message

Revision ID: ccf9590ce2e6
Revises: 314e597d5a6e
Create Date: 2018-01-31 02:17:35.190296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf9590ce2e6'
down_revision = '314e597d5a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'class_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
