"""empty message

Revision ID: d399e57f790a
Revises: f4050ab835aa
Create Date: 2018-02-09 22:19:08.266958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd399e57f790a'
down_revision = 'f4050ab835aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affix_type', 'top')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affix_type', sa.Column('top', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
