"""empty message

Revision ID: de26de15a288
Revises: 
Create Date: 2018-01-29 01:43:12.831453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de26de15a288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affix_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_percent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('affix_pct', sa.Integer(), nullable=True),
    sa.Column('chaos_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('chaos', sa.Float(), nullable=True),
    sa.Column('dynamic', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('affix_id', sa.Integer(), nullable=True),
    sa.Column('affix_min', sa.Integer(), nullable=True),
    sa.Column('affix_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affix_id'], ['affix_type.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('affix_pct', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affix_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('affix_id', sa.Integer(), nullable=True),
    sa.Column('affix_pct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affix_id'], ['affix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affix_settings')
    op.drop_table('item_settings')
    op.drop_table('affix')
    op.drop_table('item')
    op.drop_table('general_settings')
    op.drop_table('category')
    op.drop_table('affix_type')
    # ### end Alembic commands ###
