""" add item.item_type

Revision ID: f4050ab835aa
Revises: 4685c092ad95
Create Date: 2018-02-09 02:36:17.185948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4050ab835aa'
down_revision = '4685c092ad95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_type')
    # ### end Alembic commands ###
